const adventureData = [
  {
    id: 1,
    icon: "hicon hicon-regular-valley",
    title: "Ecotourism & Resort",
    count: "124 tours",
    slug: "ecotourism-resort",
  },
  {
    id: 2,
    icon: "hicon hicon-regular-meal",
    title: "Food & Culinary",
    count: "231 tours",
    slug: "food-culinary",
  },
  {
    id: 3,
    icon: "hicon hicon-culture",
    title: "In-depth Cultural",
    count: "271 tours",
    slug: "in-depth-cultural",
  },
  {
    id: 4,
    icon: "hicon hicon-mountain-view",
    title: "Explorer & Adventure",
    count: "311 tours",
    slug: "explorer-adventure",
  },
  {
    id: 5,
    icon: "hicon hicon-china-only",
    title: "Festival & Events",
    count: "219 tours",
    slug: "festival-events",
  },
  {
    id: 6,
    icon: "hicon hicon-regular-mountain-view",
    title: "Museums & Exhibitions",
    count: "189 tours",
    slug: "museums-exhibitions",
  },
  {
    id: 7,
    icon: "hicon hicon-regular-hiking",
    title: "Hiking & Trekking",
    count: "167 tours",
    slug: "hiking-trekking",
  },
  {
    id: 8,
    icon: "hicon hicon-bicycle-rental",
    title: "Motor & Bicycles",
    count: "112 tours",
    slug: "motor-bicycles",
  },
  {
    id: 9,
    icon: "hicon hicon-regular-yachting",
    title: "Ships & boats",
    count: "301 tours",
    slug: "ships-boats",
  },
  {
    id: 10,
    icon: "hicon hicon-family-with-teens",
    title: "Family Activities",
    count: "211 tours",
    slug: "family-activities",
  },
  {
    id: 11,
    icon: "hicon hicon-massage",
    title: "Health & Spa",
    count: "189 tours",
    slug: "health-spa",
  },
  {
    id: 12,
    icon: "hicon hicon-library",
    title: "Educational",
    count: "129 tours",
    slug: "educational",
  },
];
export default adventureData;
