const bookingData = {
  B0143: {
    id: "1",
    tour: "Explore Ancient Castles",
    code: "B0143",
    amount: 389.5,
    date: "May 22, 2025",
    status: "Cancelled",
    tourDetails: "Explore Ancient Castles (5 days)",
    tourDate: "Feb 21, 2024",
    guests: "4 Adults - 2 Children",
    totalAmount: 1637.5,
    requests:
      "I need to pick up my family at the airport, prepare us breakfast at the hotel.",
    fullName: "John Deep",
    email: "booking@example.com",
    phone: "+1 (0) 1 89 78 67 56",
    address: "No 234, Placer Loquen Marsei",
    city: "New York (10017)",
    country: "USA",
  },
  B0154: {
    id: "2",
    tour: "Visit the Laken Valley",
    code: "B0154",
    amount: 412.5,
    date: "May 23, 2025",
    status: "Upcoming",
    tourDetails: "Visit the Laken Valley (3 days)",
    tourDate: "July 31, 2025",
    guests: "2 Adults",
    totalAmount: 825.0,
    requests: "None",
    fullName: "John Deep",
    email: "booking@example.com",
    phone: "+1 (0) 1 89 78 67 56",
    address: "No 234, Placer Loquen Marsei",
    city: "New York (10017)",
    country: "USA",
  },
  B0165: {
    id: "3",
    tour: "City Lights Tour",
    code: "B0165",
    amount: 275.0,
    date: "May 24, 2025",
    status: "Completed",
    tourDetails: "City Lights Tour (2 days)",
    tourDate: "Mar 10, 2023",
    guests: "3 Adults - 1 Child",
    totalAmount: 935.0,
    requests: "Please arrange a guide fluent in Spanish.",
    fullName: "John Deep",
    email: "booking@example.com",
    phone: "+1 (0) 1 89 78 67 56",
    address: "No 234, Placer Loquen Marsei",
    city: "New York (10017)",
    country: "USA",
  },
  B0176: {
    id: "4",
    tour: "Mountain Trek Adventure",
    code: "B0176",
    amount: 320.0,
    date: "May 25, 2025",
    status: "Completed",
    tourDetails: "Mountain Trek Adventure (4 days)",
    tourDate: "Apr 15, 2023",
    guests: "2 Adults - 2 Children",
    totalAmount: 1080.0,
    requests: "Need vegetarian meal options.",
    fullName: "John Deep",
    email: "booking@example.com",
    phone: "+1 (0) 1 89 78 67 56",
    address: "No 234, Placer Loquen Marsei",
    city: "New York (10017)",
    country: "USA",
  },
  B0187: {
    id: "5",
    tour: "Coastal Escape",
    code: "B0187",
    amount: 450.0,
    date: "May 26, 2025",
    status: "Cancelled",
    tourDetails: "Coastal Escape (5 days)",
    tourDate: "May 20, 2023",
    guests: "4 Adults",
    totalAmount: 1800.0,
    requests: "Request ocean-view accommodation.",
    fullName: "John Deep",
    email: "booking@example.com",
    phone: "+1 (0) 1 89 78 67 56",
    address: "No 234, Placer Loquen Marsei",
    city: "New York (10017)",
    country: "USA",
  },
  B0198: {
    id: "6",
    tour: "Historic Villages Tour",
    code: "B0198",
    amount: 360.0,
    date: "May 27, 2025",
    status: "Upcoming",
    tourDetails: "Historic Villages Tour (3 days)",
    tourDate: "Jun 25, 2025",
    guests: "2 Adults - 1 Child",
    totalAmount: 900.0,
    requests: "None",
    fullName: "John Deep",
    email: "booking@example.com",
    phone: "+1 (0) 1 89 78 67 56",
    address: "No 234, Placer Loquen Marsei",
    city: "New York (10017)",
    country: "USA",
  },
  B0209: {
    id: "7",
    tour: "Wilderness Safari",
    code: "B0209",
    amount: 500.0,
    date: "May 28, 2025",
    status: "Upcoming",
    tourDetails: "Wilderness Safari (6 days)",
    tourDate: "Jul 30, 2025",
    guests: "3 Adults - 2 Children",
    totalAmount: 2000.0,
    requests: "Include binoculars for wildlife viewing.",
    fullName: "John Deep",
    email: "booking@example.com",
    phone: "+1 (0) 1 89 78 67 56",
    address: "No 234, Placer Loquen Marsei",
    city: "New York (10017)",
    country: "USA",
  },
  B0220: {
    id: "8",
    tour: "Urban Art Walk",
    code: "B0220",
    amount: 200.0,
    date: "May 29, 2025",
    status: "Cancelled",
    tourDetails: "Urban Art Walk (1 day)",
    tourDate: "Aug 10, 2023",
    guests: "2 Adults",
    totalAmount: 400.0,
    requests: "Provide a map of art locations.",
    fullName: "John Deep",
    email: "booking@example.com",
    phone: "+1 (0) 1 89 78 67 56",
    address: "No 234, Placer Loquen Marsei",
    city: "New York (10017)",
    country: "USA",
  },
  B0231: {
    id: "9",
    tour: "Wine Country Tour",
    code: "B0231",
    amount: 380.0,
    date: "May 30, 2025",
    status: "Completed",
    tourDetails: "Wine Country Tour (2 days)",
    tourDate: "Sep 15, 2023",
    guests: "4 Adults",
    totalAmount: 1520.0,
    requests: "Reserve a spot for wine tasting.",
    fullName: "John Deep",
    email: "booking@example.com",
    phone: "+1 (0) 1 89 78 67 56",
    address: "No 234, Placer Loquen Marsei",
    city: "New York (10017)",
    country: "USA",
  },
  B0242: {
    id: "10",
    tour: "Island Hopping",
    code: "B0242",
    amount: 600.0,
    date: "May 31, 2025",
    status: "Cancelled",
    tourDetails: "Island Hopping (7 days)",
    tourDate: "Oct 20, 2026",
    guests: "3 Adults - 1 Child",
    totalAmount: 2100.0,
    requests: "None",
    fullName: "John Deep",
    email: "booking@example.com",
    phone: "+1 (0) 1 89 78 67 56",
    address: "No 234, Placer Loquen Marsei",
    city: "New York (10017)",
    country: "USA",
  },
  B0253: {
    id: "11",
    tour: "Northern Lights Expedition",
    code: "B0253",
    amount: 750.0,
    date: "May 19, 2025",
    status: "Completed",
    tourDetails: "Northern Lights Expedition (5 days)",
    tourDate: "Nov 25, 2023",
    guests: "2 Adults - 2 Children",
    totalAmount: 2550.0,
    requests: "Provide warm clothing for the trip.",
    fullName: "John Deep",
    email: "booking@example.com",
    phone: "+1 (0) 1 89 78 67 56",
    address: "No 234, Placer Loquen Marsei",
    city: "New York (10017)",
    country: "USA",
  },
  B0264: {
    id: "12",
    tour: "Desert Oasis Tour",
    code: "B0264",
    amount: 420.0,
    date: "May 20, 2025",
    status: "Cancelled",
    tourDetails: "Desert Oasis Tour (4 days)",
    tourDate: "Dec 30, 2025",
    guests: "3 Adults",
    totalAmount: 1260.0,
    requests: "Arrange camel rides.",
    fullName: "John Deep",
    email: "booking@example.com",
    phone: "+1 (0) 1 89 78 67 56",
    address: "No 234, Placer Loquen Marsei",
    city: "New York (10017)",
    country: "USA",
  },
  B0275: {
    id: "13",
    tour: "Cultural Heritage Journey",
    code: "B0275",
    amount: 340.0,
    date: "May 21, 2025",
    status: "Completed",
    tourDetails: "Cultural Heritage Journey (3 days)",
    tourDate: "Jan 15, 2024",
    guests: "2 Adults - 1 Child",
    totalAmount: 850.0,
    requests: "Include a local cultural performance.",
    fullName: "John Deep",
    email: "booking@example.com",
    phone: "+1 (0) 1 89 78 67 56",
    address: "No 234, Placer Loquen Marsei",
    city: "New York (10017)",
    country: "USA",
  },
};

export default bookingData;
